# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webjeda Thunder
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thunder is a lightning fast responsive theme based on default Jekyll theme. It is minimal and free from JavaScript. It has a css file of size 5kb. 
url: "http://webjeda.com" # the base hostname & protocol for your site

baseurl: '/thunder'
permalink: /:title/

analytics: 'UA-65551407-1'

# Color schemes
color-1: '#3B97D3'
color-2: '#26B99A'


# Build settings
markdown: kramdown

sass:
    style: compressed
    
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []